#!/bin/sh

myname=db
mylongname=dbaccess
wwwdir=/mnt/etc/config/addons/www/$myname
rcddir=/mnt/etc/config/rc.d

mkdir -p /mnt

if [ "$1" == "" ]; then
    echo "CCU1"
    mount -t yaffs /dev/mtdblock3 /mnt
elif [ "$1" == "CCU2" ]; then
    echo "CCU2"
    mount -t ubifs ubi1:user /mnt
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
    echo "HM-RASPBERRYMATIC"
    mount /usr/local
    mount --bind /usr/local /mnt
fi

mkdir -p $wwwdir
cp -R $myname/* $wwwdir
chmod 775 $wwwdir

cp $mylongname $rcddir/$mylongname
chmod +x $rcddir/$mylongname

umount /mnt

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
        echo "CCU1"
        lcdtool "Reboot...             "
        lcdtool -a 0x40 -t bin 00
        echo "x" > /dev/watchdog
        reboot
        while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
        echo "CCU2"
        # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
        echo "HM-RASPBERRYMATIC"
        # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi

# signal success without requiring a reboot
exit 0
